# Generated by Django 5.1.2 on 2024-10-14 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donor',
            new_name='Dono',
        ),
    ]
